### ISSUE TITLE
Can you direct on running the Will

### ISSUE THREAD

**Issue by DGfromMTL** [dfresh613/strangerLights#1]
Can you help me out? I've got your message receiver running in Python/Django on my PI.
  
(I can see GET and POST inputs from the web page in my SSH terminal) 

![postandget](https://cloud.githubusercontent.com/assets/24196726/20870647/ab7b41be-ba59-11e6-8380-26a82cfec527.JPG)

and seem to have Arduino connected and addressable LEDs and set-up right (it's doing all the random lighting stuff in the sketch)  

But I'm confused about the Arduino Talker ... I've tried launching Will.py "pi@raspberrypi:~/arduinoTalker $ python Will.py" but it throws errors .. "No JSON object could be decoded".. I see you have three SSH windows open.. what am I missing?

![will](https://cloud.githubusercontent.com/assets/24196726/20870652/c0adc6b0-ba59-11e6-8649-37c4db400467.JPG)

 Help please.. I'm so close.﻿

**Comment by dfresh613** [comment]
It looks like you have Django listening on port 8000. However, the default Will.py query address is: self.address = "http://localhost:80/messagereceiver" (Line 9 of APIInterface.py) so it's trying to GET the message from port 80 but the response contains no data.

Since port 8000 is the default django dev server listen port, I just pushed up a change so that Will.py will now query that same port by default. You can either pull the latest code, or change the line yourself and it should be working.

I also added in better error handling for that, to indicate no data was received instead of the exception.

**Comment by DGfromMTL** [comment]
THANK YOU. It works.. Even cleared out the queue form the Message receiver!  
This has been a really great learning experience for me.. pretty much a CLI newb.. learned SSH, and a whole bunch of linux console stuff.  

Really happy. I'll share some photos of the final installations on the instructables page I found your video on.

 Great stuff.

-Dave

![yay-itworks](https://cloud.githubusercontent.com/assets/24196726/20872990/31bcf9b8-ba71-11e6-88db-78a042b77c8f.JPG)

**Comment by dfresh613** [comment]
Awesome, glad you got it working. Let me know if you encounter any bugs or something. Some additional things you can do with the raspberry pi/arduino combo in this context:

Create a cronjob, service, or script which runs on startup on your raspberry pi that will automatically start the django server, and Will.py script. (I just pushed code so Will.py won't exit if the server isn't up yet). If you do this, then you can just unplug/plug the raspberry pi in anywhere and the web server will come up, and everything should work without any SSHing.

Enable the Django server to listen on port 80. So you don't have to specify a port when accessing the web interface. 

You can also run the Django server on a cloud server somewhere, and just change ApiInterface address to query that IP. This way you can access the strangerlights interface over the internet, and not just from your home network. (Alternatively, you could port forward your raspberry pi address to access the django server over the internet.)

A good note about Django: Every django server has a builtin admin interface at /admin. Here you can add/delete messages from the queue really easily. You'll need to create a superuser id with manage.py to access the admin interface.
